### ISSUE TITLE
Colorize

### ISSUE THREAD

**Issue by cowang4** [cowang4/rusty_tree#2]
See environment variable LS_COLORS

**Comment by cowang4** [comment]
I did this for executables by using os::unix::fs::PermissionsExt

**Comment by sharkdp** [comment]
I have recently extracted the `lscolors` module from my [fd](https://github.com/sharkdp/fd) tool into a separate crate, in case you are interested:

* [`lscolors` repo](https://github.com/sharkdp/lscolors)
* [`lscolors` on crates.io](https://crates.io/crates/lscolors).

**Comment by cowang4** [comment]
That worked well, and was easy to use. Great crate!

**Comment by sharkdp** [comment]
Great to hear that, thank you for the feedback!
